version: "3.8"

services:
  nginx-kanban:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - kanban_net
    restart: always

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "15672:15672"
    networks:
      - kanban_net
    restart: always

networks:
  kanban_net:
    driver: bridge
